name: Build and test (1.249-lcm, scheduled)

on:
  schedule:
    # run every Monday, this refreshes the cache
    - cron: "13 2 * * 1"

jobs:
  python-test:
    name: Python tests
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        test: ["", "-3"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: "1.249-lcm"

      - name: Run python tests
        run: bash .github/python-nosetests${{ matrix.test }}.sh

  ocaml-test:
    name: OCaml tests
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: "1.249-lcm"

      - name: Pull configuration from xs-opam
        run: |
          curl --fail --silent https://raw.githubusercontent.com/xapi-project/xs-opam/release/stockholm/lcm/tools/xs-opam-ci.env | cut -f2 -d " " > .env

      - name: Load environment file
        id: dotenv
        uses: falti/dotenv-action@v0.2.4

      - name: Use OCaml ${{ steps.dotenv.outputs.ocaml_version_full }}
        uses: avsm/setup-ocaml@v2
        with:
          ocaml-version: ocaml-base-compiler.${{ steps.dotenv.outputs.ocaml_version_full }}
          opam-repository: ${{ steps.dotenv.outputs.repository }}
          dune-cache: true

      - name: Install dependencies
        run: opam install . --deps-only --with-test -v

      - name: Build
        run: |
          opam exec -- ./configure
          opam exec -- make
        env:
          XAPI_VERSION: v1.249.0-${{ github.sha }}

      - name: Run tests
        run: opam exec -- make test
