name: Build and test

on:
  push:
  pull_request:
  schedule:
    # run daily, this refreshes the cache
    - cron: "13 2 * * *"

jobs:
  python-test:
    name: Python tests
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        test: ["", "-3"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run python tests
        run: bash ./.github/python-nosetests${{ matrix.test }}.sh

  ocaml-test:
    name: OCaml tests
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull configuration from xs-opam
        run: curl --fail --silent https://raw.githubusercontent.com/xapi-project/xs-opam/master/tools/xs-opam-ci.env | cut -f2 -d " " > .env

      - name: Load environment file
        id: dotenv
        uses: falti/dotenv-action@v0.2.4

      - name: Use OCaml ${{ steps.dotenv.outputs.ocaml_version_full }}
        uses: avsm/setup-ocaml@v2
        with:
          ocaml-version: ocaml-base-compiler.${{ steps.dotenv.outputs.ocaml_version_full }}
          opam-repository: ${{ steps.dotenv.outputs.repository }}
          dune-cache: true

      - name: Install dependencies
        run: opam install . --deps-only --with-test --verbose

      - name: Build
        run: |
          opam exec -- ./configure
          opam exec -- make
        env:
          XAPI_VERSION: v0.0.0-${{ github.sha }}

      - name: Run tests
        run: opam exec -- make test

  deprecation-test:
    name: Deprecation tests
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate empty configuration for make to be happy
        run: touch config.mk

      - name: Number of List.hd usages has not changed
        run: make list-hd

      - name: Number of verify_cert:None usages has not changed
        run: make verify-cert
